myshop/urls.py
from django.conf.urls import url
from . import views
from .views import CreateProduct, ProductEdit

urlpatterns = [
    url(r'^$', views.ProductList, name='ProductList'),
    url(r'^stock/$', views.ProductStock, name='Stock'),
    url(r'^stock/search_tph/$', views.product_search_tph, name='search_tph'),
    url(r'^stock/searh/$', views.product_search, name='search'),
    url(r'^product/$', CreateProduct.as_view(), name='CreateProduct'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.ProductListByCategory, name='ProductListByCategory'),
    url(r'^stock/(?P<category_slug>[-\w]+)/$', views.StockListByCategory, name='StockListByCategory'),
    url(r'^(?P<category_slug>[-\w]+)/brand/(?P<brand_slug>[-\w]+)/$', views.ProductListByBrand, name='ProductListByBrand'),
    url(r'^stock/(?P<category_slug>[-\w]+)/brand/(?P<brand_slug>[-\w]+)/$', views.StockListByBrand, name='StockListByBrand'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),
    url(r'^(?P<pk>\d+)/(?P<slug>[-\w]+)/reply/(?P<id>\d+)/$', views.reply_product, name='ProductReply'),
    url(r'^product_edit/(?P<id>\d+)/(?P<slug>[-\w]+)/$', ProductEdit.as_view(), name='ProductEdit'),
    url(r'^product_delete/(?P<pk>\d+)/(?P<slug>[-\w]+)/$', views.ProductDelete, name='ProductDelete')
]

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^basket_adding/$', views.basket_adding, name='basket_adding'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^orders/$', views.order_list, name='order_list'),
    url(r'^orders/search/$', views.order_search, name='order_search'),
    url(r'^orders/search_tph/$', views.order_search_tph, name='order_search_tph'),
    url(r'^orders/(?P<pk>\d+)/product_add/$', views.product_add, name='product_add'),
    url(r'^orders/(?P<pk>\d+)/edit/$', views.order_edit, name='order_edit'),
    url(r'^orders/(?P<pk>\d+)/delete/$', views.order_delete, name='order_delete'),


]

shop/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('myshop.urls', namespace='myshop')),
    url(r'^order/', include('orders.urls', namespace='orders' )),
    url(r'^accounts/', include('accounts.urls', namespace='account')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
        urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
from django.utils.text import Truncator
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'

    def get_absolute_url(self):
        return reverse('myshop: ProductListByCategory', args=[self.slug])

    def __unicode__(self):
        return u"%s"%(self.name)

class Brand(models.Model):
    name = models.CharField(max_length=200, db_index=True, blank=True, null=True, default=None)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, blank=True, null=True, default=None)
    category = models.ForeignKey(Category, related_name='brands', verbose_name='Категорія')
    class Meta:
        ordering = ['name']
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренди'


    def __unicode__(self):
        return u"%s"%(self.name)


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', verbose_name='Категорія', blank=True, null=True, default=None)
    brand = models.ForeignKey(Brand, related_name='products', verbose_name='Бренд', blank=True, null=True, default=None)
    name = models.CharField(max_length=200, db_index=True, verbose_name='Назва')
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True, verbose_name='Зображення товару')
    description = models.TextField(blank=True, verbose_name='Опис товару')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Ціна')
    stock = models.PositiveIntegerField(verbose_name='На складі')
    available = models.BooleanField(default=True, verbose_name='Доступний')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        index_together = [['id', 'slug']]
        verbose_name = 'Товар'
        verbose_name_plural = 'Товари'

    def get_absolute_url(self):
        return reverse('myshop:ProductDetail', args=[self.id, self.slug])

    def __unicode__(self):
        return u"%s"%(self.name)

class Reply(models.Model):
    message = models.TextField(max_length=4000, verbose_name='коментар')
    product = models.ForeignKey(Product, related_name='replies')
    author = models.ForeignKey(User, related_name='replies')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    parent = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = 'Коментар'
        verbose_name_plural = 'Коментарі'

    def __unicode__(self):
        reply = Truncator(self.message).chars(30)
        return u"%s"%(reply)

myshop/forms.py
from django import forms
from .models import Reply

class ReplyForm(forms.ModelForm):

    class Meta:
        model = Reply
        fields = ['message',]

myshop/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.views.generic import CreateView, UpdateView
from .models import Category, Product, Brand, Reply
from django.utils.text import slugify
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from django.template.loader import render_to_string
from .util import paginate
from .forms import ReplyForm
import json

# Create your views here.

def ProductList(request, category_slug=None):

    products = Product.objects.filter(available=True)
    context = paginate(products, 4, request, {}, var_name='products')
    return render(request, 'myshop/product/list.html',context )

def ProductStock(request):
    products = Product.objects.all()
    return render(request, 'myshop/product/stock.html', locals())

def ProductListByCategory(request, category_slug ):
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(available=True, category=category)
        brands = Brand.objects.filter(category=category)
        context = paginate(products, 4, request, {}, var_name='products')
    return render(request, 'myshop/product/list_by_category.html', context)

def StockListByCategory(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    context = {'products': products}
    data = dict()
    data['html_form'] = render_to_string('myshop/product/includes/partial_stock_list.html', context, request)
    return JsonResponse(data)


def ProductListByBrand(request, category_slug, brand_slug ):

    if category_slug:
        brands = get_object_or_404(Brand, category__slug=category_slug, slug=brand_slug)
        products = Product.objects.filter(available=True, brand=brands)
        context = paginate(products, 4, request, {}, var_name='products')
    return render(request, 'myshop/product/list_by_brand.html', context)

def StockListByBrand(request, category_slug, brand_slug):
    brands = get_object_or_404(Brand, category__slug=category_slug, slug=brand_slug)
    products = Product.objects.filter(available=True, brand=brands)
    context = {'products': products}
    data = dict()
    data['html_form'] = render_to_string('myshop/product/includes/partial_stock_list.html', context, request)
    return JsonResponse(data)


def ProductDetail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()
    replies = Reply.objects.filter(product=product)
    return render(request, 'myshop/product/detail.html', {'product': product, 'replies': replies})

class CreateProduct(CreateView):
    model = Product
    fields = ('category', 'brand', 'name', 'image', 'description', 'price', 'stock', 'available',)
    template_name = 'myshop/product/create_product.html'

    def form_valid(self, form):

        model = form.save(commit=False)
        model.slug = slugify(model.name)
        model.save()
        return redirect('myshop:CreateProduct')

class ProductEdit(UpdateView):
    model = Product
    fields = fields = ['name', 'category', 'brand', 'description', 'price', 'stock', 'image']
    template_name = 'myshop/product/product_edit.html'

    def get_success_url(self):
        return reverse('myshop:Stock')

def ProductDelete(request, pk, slug):
    product = get_object_or_404(Product, pk=pk, slug=slug)
    data = dict()
    if request.method == 'POST':
        product.delete()
        data['form_is_valid'] = True
        products = Product.objects.all()
        data['html_order_list'] = render_to_string('myshop/product/includes/partial_stock_list.html', {'products': products})
    else:
        context = {'product': product}
        data['html_form'] = render_to_string('myshop/product/product_delete.html', context, request)
    return JsonResponse(data)


def product_search_tph(request):
    q = request.GET.get('q', '')
    products = Product.objects.filter(name__icontains=q)
    data = []
    for product in products:
        new = {'q': product.name}
        if not new in data:
            data.append(new)
    return HttpResponse(json.dumps(data), content_type="application/json")

def product_search(request):
    data = dict()
    if request.method == 'POST':
        search = request.POST.get('search_product')
        products = Product.objects.filter(name__iexact=search)
        data['form_is_valid'] = True
        data['html_order_list'] = render_to_string('myshop/product/includes/partial_stock_list.html', {'products': products})

    return JsonResponse(data)

def reply_product(request, pk, slug, id):
    product = get_object_or_404(Product, pk=pk, slug=slug)
    data = dict()
    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            reply, created = Reply.objects.get_or_create(product=product, message=form.cleaned_data.get('message'), author=request.user)
            if int(id) > 0:
                reply.parent = int(id)
                reply.save()
            replies = Reply.objects.filter(product=product)
            data['form_is_valid'] = True

            data['html_order_list'] = render_to_string('myshop/product/includes/partial_replay_list.html', {'replies': replies, 'product': product})
    else:
        form = ReplyForm
        context = {'form': form, 'product': product}
        data['html_form'] = render_to_string('myshop/product/reply_add.html', context, request)
    return JsonResponse(data)

templates/myshop/product/create_product.html
{% extends 'myshop/base.html' %}

{% block content %}
<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        {% include 'myshop/product/includes/partial_form.html' %}
    </div>
    <div class="form-group">
        <a class="button" href="{% url 'myshop:ProductList' %}">Скасувати</a>
        <button type="submit" class="btn btn-primary">Створити продукт</button>
    </div>
</form>

{% endblock content %}

templates/myshop/product/detail.html
{% extends "myshop/base.html" %}
{% load static %}
{% block title %}
  {{ product.name }}
{% endblock %}
{% block content %}
  <div class="product-detail ">

      <div class="col-sm-8">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no-image.png'%}{% endif %}" class="img-responsive increase" width="250" height="300" alt="{{product.name}}">
      </div>

    <div class="row">
    <div class="col-sm-8">
      <h2>{{ product.name }}</h2>
      <h2><a href="#">{{ product.category }}</a></h2>
      <p class="price">
        {{ product.price }} грн.
      </p>
      <span>
        {{ product.description | linebreaks}}
      </span>
    </div>
    <div class="col-sm-4">
      <form id="form_buying_product" class="form-inline" action="{% url 'orders:basket_adding' %}">{% csrf_token %}
        <div class="form-group">
          <input type="number" class="form-control" id="number" name="number" value="1">
        </div>
        <div class="form-group">
            <button type="submit" id="submit_btn" class="btn btn-success btn-buy"
                    data-product_id = "{{ product.id }}"
                    data-name = "{{ product.name }}"
                    data-price = "{{ product.price }}"
            >
              Купити</button>
        </div>
      </form>
    </div>
    </div>
    <br>
    <br>
    {% if user.is_authenticated %}
    <div class="col-sm-4" id="reply_add">
        <h4>Відгуки про товар</h4> <button data-url="{% url 'myshop:ProductReply' product.id product.slug 0 %}" class="btn btn-primary js-create-reply">Додати</button>
    </div>
    {% endif %}
    <div id="reply_list">
      {% include 'myshop/product/includes/partial_replay_list.html' %}
    </div>
  </div>

<!-- Modal window -->
    <div class="modal fade" id="modal-order">
        <div class="modal-dialog">
            <div class="modal-content">

            </div>
        </div>
    </div>
{% endblock content %}
{% block extra_js %}
<script src="{% static 'js/product.js' %}"></script>

{% endblock extra_js %}

templates/myshop/product/list.html
{% extends 'myshop/base.html' %}
{% load static %}
{% load myshop_extras %}
{% block title %}
  {% if category %} {{ category.name }} {% else %} Сторінка товарів{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar" class="col-sm-3">
    <h3>Категорії</h3>
    <ul>
      <li {% if not category %} class="selected" {% endif %}>
        <a href="{% url 'myshop:ProductList' %}">Всі</a>
      </li>
      {% for cat in categories %}
        <li>
          <a href="{% url 'myshop:ProductListByCategory' cat.slug %}">{{ cat.name }}</a>
          <ul> {% for brand in cat.brands|in_category:cat %}
            <li>
              <a href="{% url 'myshop:ProductListByBrand' cat.slug brand.slug %}">{{ brand.name }}</a>
            </li>
               {% endfor %}
          </ul>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product_list col-md-9">
    <h2>{% if category %}{{ category.name }}{% else %}Товари{% endif %}</h2>
  </div>
  <div class="products">
    <div class="items row">
      {% for product in products %}
        <div class="item col-md-3">
          <div class="card border-secondary" style="width: 18rem;">
            <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no-image-02.jpg' %}{% endif %}" class="card-img-top img-responsive" width="250" height="300">
          </a>
            <div class="card-body">
              <a href="{% url 'myshop:ProductDetail' product.id product.slug %}">{{ product.name }}</a><br>
              {{ product.price }} грн.
            </div>
          </div>

        </div>
      {% endfor %}
    </div>
  </div>
  {% if products.has_next %}
    <div class="text-center">
    <a class="btn btn-success load-more" href="?page={{ products.next_page_number }}" data-pages={{paginator.num_pages}} >Завантажити<br>ще </a>
    </div>
  {% endif %}

{% endblock %}

templates/myshop/product/list_by_brand.html
{% extends 'myshop/base.html' %}
{% load static %}


{% block content %}
  <div class="container products">
    <div class="items row">
      {% for product in products %}
        <div class="item col-md-3">
          <div class="card border-secondary" style="width: 18rem;">
            <a href="{{ product.get_absolute_url }}">
              <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no-image-02.jpg' %}{% endif %}" class="card-img-top img-responsive" width="250" height="300">
            </a>
            <div class="card-body">
              <a href="{% url 'myshop:ProductDetail' product.id product.slug %}">{{ product.name }}</a><br>
              {{ product.price }} грн.
            </div>
          </div>

        </div>
      {% endfor %}
    </div>
  </div>

  {% if products.has_next %}
    <div class="text-center">
      <a class="btn btn-success load-more" href="?page={{ products.next_page_number }}" data-pages={{paginator.num_pages}} >Завантажити<br>ще </a>
    </div>
  {% endif %}
{% endblock %}

templates/myshop/product/list_by_category.html
{% extends 'myshop/base.html' %}
{% load static %}

{% block title %}
  {% if category %} {{ category.name }} {% else %} Сторінка товарів{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar" class="col-sm-3">
    <h3>Категории</h3>
    <ul>
      <li {% if not category %} class="selected" {% endif %}>
        <a href="{% url 'myshop:ProductList' %}">Всі </a>
      </li>
      {% for brand in brands %}
        <li {% if category.slug == cat.slug %} class="selected" {% endif %}>
          <a href="{% url 'myshop:ProductListByBrand' category.slug brand.slug %}">{{ brand.name }}Brand</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product_list products">
    <h2>{% if category %}{{ category.name }}{% else %}Товари{% endif %}</h2>
    <div class="items row">
      {% for product in products %}
        <div class="item col-md-3">
          <div class="card border-secondary" style="width: 18rem;">
            <a href="{{ product.get_absolute_url }}">
              <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no-image-02.jpg' %}{% endif %}" class="card-img-top img-responsive" width="250" height="300">
            </a>
            <div class="card-body">
              <a href="{% url 'myshop:ProductDetail' product.id product.slug %}">{{ product.name }}</a><br>
              {{ product.price }} грн.
            </div>
          </div>

        </div>
      {% endfor %}
    </div>
</div>

  {% if products.has_next %}
    <div class="text-center">
      <a class="btn btn-success load-more" href="?page={{ products.next_page_number }}" data-pages={{paginator.num_pages}} >Завантажити<br>ще </a>
    </div>
  {% endif %}
{% endblock %}

templates/myshop/product/product_delete.html
<form method="post" action="{% url 'myshop:ProductDelete' product.id product.slug %}" class="js-order-delete-form">
  {% csrf_token %}
  <div class="mod-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="mod-title">Видалення товар</h4>
  </div>
  <div class="mod-body">
    <p class="lead">Ви впевнені у видаленні товару {{ product.name }}<strong></strong>?</p>
  </div>
  <div class="mod-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Скасувати</button>
    <button type="submit" class="btn btn-danger">Видалити</button>
  </div>
</form>

templates/myshop/product/product_edit.html
{% extends 'myshop/base.html' %}
{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="form-group">
            {% include 'myshop/product/includes/partial_form.html' %}
        </div>
    <div class="form-group">
        <a class="button" href="{% url 'myshop:Stock' %}">Скасувати</a>
        <button type="submit" class="btn btn-danger">Добавити</button>
    </div>
</form>
{% endblock content %}

templates/myshop/product/reply_add.html
<form method="post" class="form-horizontal js-reply-create-form" action="" id="form">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Додати коментар</h4>
    </div>
    <div class="modal-body">
    {% include 'myshop/product/includes/partial_form.html' %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Скасувати</button>
        <button type="submit" class="btn btn-primary" data-reload="{% url 'myshop:ProductDetail' product.id product.slug %}" id="submit" >Додати коментар</button>
    </div>
</form>

templates/myshop/product/stock.html
{% extends 'myshop/base.html' %}
{% load static %}
{% load myshop_extras %}
{% block title %}
  {% if category %} {{ category.name }} {% else %} Сторінка товарів{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar" class="col-sm-3">
    <h3>Категории</h3>
    <ul>
      <li {% if not category %} class="selected" {% endif %}>
        <a href="{% url 'myshop:Stock' %}">Всі</a>
      </li>
      {% for cat in categories %}
        <li>
          <a href="{% url 'myshop:StockListByCategory' cat.slug %}" class="load-page">{{ cat.name }}</a>
          <ul> {% for brand in cat.brands|in_category:cat %}
            <li>
              <a href="{% url 'myshop:StockListByBrand' cat.slug brand.slug %}" class="load-page">{{ brand.name }}</a>
            </li>
               {% endfor %}
          </ul>
        </li>
      {% endfor %}
    </ul>
  </div>
    <form method="post" action="{% url 'myshop:search' %}"  id="search_product">
        {% csrf_token %}
        <input class="w3-input w3-border typeahead" name="search_product" id="search" type="text" value="" placeholder="Введіть назву">
        <button type="submit" class="btn btn-primary" name="search_button" >Пошук</button>

    </form>
<br>
<br>
<table class="table" id="order-table">
    <thead class="thead-inverse">
        <tr>
            <th>№</th>
            <th>Назва</th>
            <th>Категорія</th>
            <th>Бренд</th>
            <th>Ціна</th>
            <th>На складі</th>
            <th>Доступний</th>
            <th>Створено</th>
            <th>Оновлено</th>
            <th>Дія</th>
        </tr>
    </thead>
    <tbody>
        {% include 'myshop/product/includes/partial_stock_list.html' %}
    </tbody>
</table>
<!-- Modal window -->
    <div class="modal fade" id="modal-order">
        <div class="modal-dialog">
            <div class="modal-content">

            </div>
        </div>
    </div>
{% endblock %}
{% block extra_js %}
    <script src="{% static 'js/stock.js' %}"></script>
{% endblock extra_js %}