myshop/urls.py
from django.conf.urls import url
from . import views
from .views import CreateProduct, ProductEdit

urlpatterns = [
    url(r'^$', views.ProductList, name='ProductList'),
    url(r'^stock/$', views.ProductStock, name='Stock'),
    url(r'^stock/search_tph/$', views.product_search_tph, name='search_tph'),
    url(r'^stock/searh/$', views.product_search, name='search'),
    url(r'^product/$', CreateProduct.as_view(), name='CreateProduct'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.ProductListByCategory, name='ProductListByCategory'),
    url(r'^stock/(?P<category_slug>[-\w]+)/$', views.StockListByCategory, name='StockListByCategory'),
    url(r'^(?P<category_slug>[-\w]+)/brand/(?P<brand_slug>[-\w]+)/$', views.ProductListByBrand, name='ProductListByBrand'),
    url(r'^stock/(?P<category_slug>[-\w]+)/brand/(?P<brand_slug>[-\w]+)/$', views.StockListByBrand, name='StockListByBrand'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),
    url(r'^(?P<pk>\d+)/(?P<slug>[-\w]+)/reply/(?P<id>\d+)/$', views.reply_product, name='ProductReply'),
    url(r'^product_edit/(?P<id>\d+)/(?P<slug>[-\w]+)/$', ProductEdit.as_view(), name='ProductEdit'),
    url(r'^product_delete/(?P<pk>\d+)/(?P<slug>[-\w]+)/$', views.ProductDelete, name='ProductDelete')
]

shop/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('myshop.urls', namespace='myshop')),
    url(r'^order/', include('orders.urls', namespace='orders' )),
    url(r'^accounts/', include('accounts.urls', namespace='account')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
        urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/myshop/product/includes/partial_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %} col-lg-4">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

templates/myshop/product/includes/partial_replay_list.html
{% for reply in replies %}
<div class="card col-md-6">
    <div class="card-header text-white bg-dark py-2 px-3"></div>
    <div class="card-body p-3">
        <div class="row mb-6">
            <div class="col-md-2">
                <small>{{ reply.created}}</small>
                {{ reply.author.username }}
            </div>
            <div class="col-md-10">
                {% if reply.parent %} <small>відповідь для
                    {% for rep in replies %}
                        {% if rep.id == reply.parent  %}
                            {{ rep.author.username }}
                        {% endif %}
                    {% endfor %}
                <br></small> {% endif %}

                {{ reply.message }}
                {% if user.is_authenticated %}
                <div class="text-right answer">
                <small>
                    <button data-url="{% url 'myshop:ProductReply' product.id product.slug reply.id %}" class="btn btn-primary js-create-reply">Відповісти</button>
                </small>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<br>
<br>
{% endfor %}

templates/myshop/product/includes/partial_stock_list.html
{% for product in products %}
        <tr>
            <td><a href="">{{ forloop.counter }}</a></td>
            <td>{{ product.name }}</td>
            <td>{{ product.category }}</td>
            <td>{{ product.brand }}</td>
            <td>{{ product.price }}</td>
            <td>{{ product.stock }}</td>
            <td>{{ product.available }}</td>
            <td>{{ product.created }}</td>
            <td>{{ product.updated }}</td>
            <td>
                <div class="btn-group">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Дія
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu" >
                        <li><a href="{% url 'myshop:ProductEdit' product.id product.slug %}">Редагувати</a></li>
                        <li><a href="" class="btn btn-danger js-delete-order" data-url="{% url 'myshop:ProductDelete' product.id product.slug %}">Видалити</a></li>

                    </ul>
                </div>
            </td>
        </tr>
{% endfor %}