accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views as accounts_views


urlpatterns = [
    url(r'^signup/$', accounts_views.signup, name='signup'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='myshop/account/login.html'), name='login'),
    url(r'^account/$', accounts_views.update_profile, name='my_account'),

    url(r'^reset/$', auth_views.PasswordResetView.as_view(template_name='myshop/account/password_reset.html',success_url='/accounts/reset/done/', email_template_name='myshop/account/password_reset_email.html', subject_template_name='myshop/account/password_reset_subject.txt'), name='password_reset'),
    url(r'^reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name='myshop/account/password_reset_done.html'), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',	auth_views.PasswordResetConfirmView.as_view(template_name='myshop/account/password_reset_confirm.html', success_url='/accounts/reset/complete/'), name='password_reset_confirm'),
    url(r'^reset/complete/$', auth_views.PasswordResetCompleteView.as_view(template_name='myshop/account/password_reset_complete.html'),name='password_reset_complete'),

]

myshop/urls.py
from django.conf.urls import url
from . import views
from .views import CreateProduct, ProductEdit

urlpatterns = [
    url(r'^$', views.ProductList, name='ProductList'),
    url(r'^stock/$', views.ProductStock, name='Stock'),
    url(r'^stock/search_tph/$', views.product_search_tph, name='search_tph'),
    url(r'^stock/searh/$', views.product_search, name='search'),
    url(r'^product/$', CreateProduct.as_view(), name='CreateProduct'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.ProductListByCategory, name='ProductListByCategory'),
    url(r'^stock/(?P<category_slug>[-\w]+)/$', views.StockListByCategory, name='StockListByCategory'),
    url(r'^(?P<category_slug>[-\w]+)/brand/(?P<brand_slug>[-\w]+)/$', views.ProductListByBrand, name='ProductListByBrand'),
    url(r'^stock/(?P<category_slug>[-\w]+)/brand/(?P<brand_slug>[-\w]+)/$', views.StockListByBrand, name='StockListByBrand'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),
    url(r'^(?P<pk>\d+)/(?P<slug>[-\w]+)/reply/(?P<id>\d+)/$', views.reply_product, name='ProductReply'),
    url(r'^product_edit/(?P<id>\d+)/(?P<slug>[-\w]+)/$', ProductEdit.as_view(), name='ProductEdit'),
    url(r'^product_delete/(?P<pk>\d+)/(?P<slug>[-\w]+)/$', views.ProductDelete, name='ProductDelete')
]

shop/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('myshop.urls', namespace='myshop')),
    url(r'^order/', include('orders.urls', namespace='orders' )),
    url(r'^accounts/', include('accounts.urls', namespace='account')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
        urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class StProfile(models.Model):
    user = models.OneToOneField(User)

    class Meta(object):
        verbose_name= u"Профіль користувача"

    mobile_phone = models.CharField(
        max_length= 12,
        blank= True,
        verbose_name= u"Мобільний телефон",
        default=''
    )

    def __unicode__(self):
        return self.user.username

myshop/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
from django.utils.text import Truncator
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'

    def get_absolute_url(self):
        return reverse('myshop: ProductListByCategory', args=[self.slug])

    def __unicode__(self):
        return u"%s"%(self.name)

class Brand(models.Model):
    name = models.CharField(max_length=200, db_index=True, blank=True, null=True, default=None)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, blank=True, null=True, default=None)
    category = models.ForeignKey(Category, related_name='brands', verbose_name='Категорія')
    class Meta:
        ordering = ['name']
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренди'


    def __unicode__(self):
        return u"%s"%(self.name)


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', verbose_name='Категорія', blank=True, null=True, default=None)
    brand = models.ForeignKey(Brand, related_name='products', verbose_name='Бренд', blank=True, null=True, default=None)
    name = models.CharField(max_length=200, db_index=True, verbose_name='Назва')
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True, verbose_name='Зображення товару')
    description = models.TextField(blank=True, verbose_name='Опис товару')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Ціна')
    stock = models.PositiveIntegerField(verbose_name='На складі')
    available = models.BooleanField(default=True, verbose_name='Доступний')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        index_together = [['id', 'slug']]
        verbose_name = 'Товар'
        verbose_name_plural = 'Товари'

    def get_absolute_url(self):
        return reverse('myshop:ProductDetail', args=[self.id, self.slug])

    def __unicode__(self):
        return u"%s"%(self.name)

class Reply(models.Model):
    message = models.TextField(max_length=4000, verbose_name='коментар')
    product = models.ForeignKey(Product, related_name='replies')
    author = models.ForeignKey(User, related_name='replies')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    parent = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = 'Коментар'
        verbose_name_plural = 'Коментарі'

    def __unicode__(self):
        reply = Truncator(self.message).chars(30)
        return u"%s"%(reply)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import StProfile

class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = StProfile
        fields = ('mobile_phone',)

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','email','username')

myshop/forms.py
from django import forms
from .models import Reply

class ReplyForm(forms.ModelForm):

    class Meta:
        model = Reply
        fields = ['message',]

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login as auth_login
from .forms import SignUpForm, ProfileForm, UserForm
from .models import StProfile
from django.contrib.auth.models import User
# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user,backend='django.contrib.auth.backends.ModelBackend')
            return redirect('myshop:ProductList')
    else:
        form = SignUpForm()
    return render(request, 'myshop/account/signup.html', {'form': form})

def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.stprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

        return HttpResponseRedirect(reverse('myshop:ProductList'))
            #render(request, 'students/my_account.html',{'user_form': user_form, 'profile_form': profile_form})
    else:
        user_id = User.objects.get(pk= request.user.pk)
        user_form = UserForm(instance= request.user)
        user_id.stprofile, created = StProfile.objects.get_or_create(user=user_id)
        profile_form = ProfileForm(instance= request.user.stprofile)
    return render(request, 'myshop/account/my_account.html',{'user_form': user_form, 'profile_form': profile_form} )

myshop/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.views.generic import CreateView, UpdateView
from .models import Category, Product, Brand, Reply
from django.utils.text import slugify
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from django.template.loader import render_to_string
from .util import paginate
from .forms import ReplyForm
import json

# Create your views here.

def ProductList(request, category_slug=None):

    products = Product.objects.filter(available=True)
    context = paginate(products, 4, request, {}, var_name='products')
    return render(request, 'myshop/product/list.html',context )

def ProductStock(request):
    products = Product.objects.all()
    return render(request, 'myshop/product/stock.html', locals())

def ProductListByCategory(request, category_slug ):
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(available=True, category=category)
        brands = Brand.objects.filter(category=category)
        context = paginate(products, 4, request, {}, var_name='products')
    return render(request, 'myshop/product/list_by_category.html', context)

def StockListByCategory(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    context = {'products': products}
    data = dict()
    data['html_form'] = render_to_string('myshop/product/includes/partial_stock_list.html', context, request)
    return JsonResponse(data)


def ProductListByBrand(request, category_slug, brand_slug ):

    if category_slug:
        brands = get_object_or_404(Brand, category__slug=category_slug, slug=brand_slug)
        products = Product.objects.filter(available=True, brand=brands)
        context = paginate(products, 4, request, {}, var_name='products')
    return render(request, 'myshop/product/list_by_brand.html', context)

def StockListByBrand(request, category_slug, brand_slug):
    brands = get_object_or_404(Brand, category__slug=category_slug, slug=brand_slug)
    products = Product.objects.filter(available=True, brand=brands)
    context = {'products': products}
    data = dict()
    data['html_form'] = render_to_string('myshop/product/includes/partial_stock_list.html', context, request)
    return JsonResponse(data)


def ProductDetail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()
    replies = Reply.objects.filter(product=product)
    return render(request, 'myshop/product/detail.html', {'product': product, 'replies': replies})

class CreateProduct(CreateView):
    model = Product
    fields = ('category', 'brand', 'name', 'image', 'description', 'price', 'stock', 'available',)
    template_name = 'myshop/product/create_product.html'

    def form_valid(self, form):

        model = form.save(commit=False)
        model.slug = slugify(model.name)
        model.save()
        return redirect('myshop:CreateProduct')

class ProductEdit(UpdateView):
    model = Product
    fields = fields = ['name', 'category', 'brand', 'description', 'price', 'stock', 'image']
    template_name = 'myshop/product/product_edit.html'

    def get_success_url(self):
        return reverse('myshop:Stock')

def ProductDelete(request, pk, slug):
    product = get_object_or_404(Product, pk=pk, slug=slug)
    data = dict()
    if request.method == 'POST':
        product.delete()
        data['form_is_valid'] = True
        products = Product.objects.all()
        data['html_order_list'] = render_to_string('myshop/product/includes/partial_stock_list.html', {'products': products})
    else:
        context = {'product': product}
        data['html_form'] = render_to_string('myshop/product/product_delete.html', context, request)
    return JsonResponse(data)


def product_search_tph(request):
    q = request.GET.get('q', '')
    products = Product.objects.filter(name__icontains=q)
    data = []
    for product in products:
        new = {'q': product.name}
        if not new in data:
            data.append(new)
    return HttpResponse(json.dumps(data), content_type="application/json")

def product_search(request):
    data = dict()
    if request.method == 'POST':
        search = request.POST.get('search_product')
        products = Product.objects.filter(name__iexact=search)
        data['form_is_valid'] = True
        data['html_order_list'] = render_to_string('myshop/product/includes/partial_stock_list.html', {'products': products})

    return JsonResponse(data)

def reply_product(request, pk, slug, id):
    product = get_object_or_404(Product, pk=pk, slug=slug)
    data = dict()
    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            reply, created = Reply.objects.get_or_create(product=product, message=form.cleaned_data.get('message'), author=request.user)
            if int(id) > 0:
                reply.parent = int(id)
                reply.save()
            replies = Reply.objects.filter(product=product)
            data['form_is_valid'] = True

            data['html_order_list'] = render_to_string('myshop/product/includes/partial_replay_list.html', {'replies': replies, 'product': product})
    else:
        form = ReplyForm
        context = {'form': form, 'product': product}
        data['html_form'] = render_to_string('myshop/product/reply_add.html', context, request)
    return JsonResponse(data)

templates/myshop/account/login.html
{% extends "myshop/base.html" %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}" type="text/css">
{% endblock extra_css %}
{% block title %}Вхід{% endblock title %}
{% block content %}
<div class="container">
 <form  action="{% url 'account:login' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{% url 'myshop:ProductList' %}">

    <div class="form-group row">
        <label class="col-sm-2" for="login">Ваш логін</label>
        <div class="col-sm-3">
            <input type="text" class="form-control" id="login" value="" name="username">
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2" for="password">Пароль</label>
        <div class="col-sm-3">
            <input type="password" class="form-control" id="password" value="" name="password">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-5">
            <button type="submit" class="btn btn-primary">Вхід</button>
            <a href="{% url 'myshop:ProductList' %}" class="btn btn-default" role="button">Скасувати</a>
            <br>
            <small>
                <a href="{% url 'account:password_reset' %}">Забули пароль ?</a>
            </small>
        </div>
    </div>
 </form>
</div>
{% endblock content %}

templates/myshop/account/my_account.html
{% load static  %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock extra_css %}
{% block title %}{% endblock title %}
{% block content %}
<br>
<br>
 <form  action="{% url 'account:my_account' %}" method="post" class="w3-container w3-card-4 w3-light-grey w3-text-blue " >
    {% csrf_token %}
    <h2 class="w3-center">Мій акакунт {{ user.username }}</h2>
    <div class="w3-row w3-section">
       <label class="col-sm-2" for="first_name">Ім'я</label>

        <div class="w3-rest">
            <input type="text" class="w3-input w3-border" id="first_name"  name="first_name" value="{{ user.first_name }}">
        </div>

    </div>
    <div class="w3-row w3-section">
        <label class="col-sm-2" for="last_name">Прізвище</label>
        <div class="w3-rest">
            <input type="text" class="w3-input w3-border" id="last_name" value="{{ user.last_name }}" name="last_name" >
        </div>
    </div>
     <div class="w3-row w3-section">
        <label class="col-sm-2" for="email">Поштова скринька</label>
        <div class="w3-rest">
            <input type="text" class="w3-input w3-border" id="email" value="{{ user.email }}" name="email" placeholder="">
        </div>
    </div>
    <div class="w3-row w3-section">
        <label class="col-sm-2" for="username">Користувач</label>
        <div class="w3-rest">
            <input type="text" class="w3-input w3-border" id="username" value="{{ user.username }}" name="username" placeholder="">
        </div>
    </div>
    <div class="w3-row w3-section">
        <label class="col-sm-2" for="mobile_phone">Телефон</label>
        <div class="w3-rest">
            <input type="text" class="w3-input w3-border" id="mobile_phone" value="{{ user.stprofile.mobile_phone }}" name="mobile_phone" placeholder="">
        </div>
    </div>
    <div class="w3-row w3-section">
        <div class="col-sm-5">
            <button type="submit" class="w3-button w3-block w3-section w3-blue w3-ripple w3-padding">Оновити</button>
            <a href="{% url 'myshop:ProductList' %}" class="w3-button w3-block w3-section w3-orange w3-ripple w3-padding" role="button">Скасувати</a>

        </div>
    </div>
 </form>

{% endblock content %}

templates/myshop/account/password_reset.html
{% extends "myshop/base.html" %}

{% load static from staticfiles %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock extra_css %}
{% block title %}Зміна пароля {{ user.username }}{% endblock title %}
{% block content %}


  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Забули пароль?</h3>
          <p>Вкажіть адресу вашої поштової скриньки і ми вишлемо лінк для зміни пароля.</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'myshop/product/includes/partial_form.html' %}
            <button type="submit" class="btn btn-primary ">Відправити</button>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/myshop/account/password_reset_complete.html
{% extends "myshop/base.html" %}
{% load static %}
{% block extra_css %}
{% endblock extra_css %}
{% block title %}Пароль змінено{% endblock title %}
{% block content %}
 <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Пароль змінено!</h3>
          <div class="alert alert-success" role="alert">
            Ви можете зайти на сайт з новим паролем.
          </div>
          <a href="{% url 'account:login' %}" class="btn btn-secondary btn-block">Повернутися до  log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/myshop/account/password_reset_confirm.html
{% extends "myshop/base.html" %}

{% load static from staticfiles %}
{% block extra_css %}

{% endblock extra_css %}
{% block title %}Зміна пароля {{ user.username }}{% endblock title %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h3 class="card-title">Зміна пароля для {{ form.user.username }}</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'myshop/product/includes/partial_form.html' %}
              <button type="submit" class="btn btn-success btn-block">Змінити пароль</button>
            </form>
          {% else %}
            <h3 class="card-title">Reset your password</h3>
            <div class="alert alert-danger" role="alert">
              It looks like you clicked on an invalid password reset link. Please try again.
            </div>
            <a href="{% url 'account:password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset link</a>
          {% endif %}
        </div>
      </div>
    </div>
 </div>
{% endblock content %}

templates/myshop/account/password_reset_done.html
{% extends "myshop/base.html" %}

{% load static from staticfiles %}
{% block extra_css %}

{% endblock extra_css %}
{% block title %}Мій акаунт {{ user.username }}{% endblock title %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Зміна вашого пароля</h3>
          <p>Перевірте вашу скриньку і перейдіть по отриманому лінку . </p>
          <a href="{% url 'account:login' %}" class="btn btn-secondary btn-block">або поверніться до Log in</a>
        </div>
      </div>
    </div>
</div>
{% endblock content %}

templates/myshop/account/password_reset_email.html
Привіт друже,

Someone asked for a password reset for the email address {{ email }}. Follow the link below:
{{ protocol }}://{{ domain }}{% url 'account:password_reset_confirm' uidb64=uid token=token %}

In case you forgot your  username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL in a new browser window instead.

If you've received this mail in error, it's likely that another user entered your email address by mistake while trying
to reset a password. If you didn't initiate the request, you don't need to take any further action and can safely
disregard this email.

templates/myshop/account/signup.html
{% extends "myshop/base.html" %}
{% load static  %}
{% block title %}Реєстрація{% endblock title %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock extra_css %}

{% block content %}
<div class="container">
    <h2>Реєстрація</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        {% include 'myshop/product/includes/partial_form.html' %}

        <button type="submit" class="btn btn-primary">Створити акаунт</button>
        <a href="{% url 'myshop:ProductList' %}" class="btn btn-default" role="button">Скасувати</a>
    </form>
    <div class="text-center">
        вже є акаунт <a href="{% url 'account:login' %}">Log in</a>

    </div>
</div>


{% endblock content %}