accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views as accounts_views


urlpatterns = [
    url(r'^signup/$', accounts_views.signup, name='signup'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='myshop/account/login.html'), name='login'),
    url(r'^account/$', accounts_views.update_profile, name='my_account'),

    url(r'^reset/$', auth_views.PasswordResetView.as_view(template_name='myshop/account/password_reset.html',success_url='/accounts/reset/done/', email_template_name='myshop/account/password_reset_email.html', subject_template_name='myshop/account/password_reset_subject.txt'), name='password_reset'),
    url(r'^reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name='myshop/account/password_reset_done.html'), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',	auth_views.PasswordResetConfirmView.as_view(template_name='myshop/account/password_reset_confirm.html', success_url='/accounts/reset/complete/'), name='password_reset_confirm'),
    url(r'^reset/complete/$', auth_views.PasswordResetCompleteView.as_view(template_name='myshop/account/password_reset_complete.html'),name='password_reset_complete'),

]

myshop/urls.py
from django.conf.urls import url
from . import views
from .views import CreateProduct, ProductEdit

urlpatterns = [
    url(r'^$', views.ProductList, name='ProductList'),
    url(r'^stock/$', views.ProductStock, name='Stock'),
    url(r'^stock/search_tph/$', views.product_search_tph, name='search_tph'),
    url(r'^stock/searh/$', views.product_search, name='search'),
    url(r'^product/$', CreateProduct.as_view(), name='CreateProduct'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.ProductListByCategory, name='ProductListByCategory'),
    url(r'^stock/(?P<category_slug>[-\w]+)/$', views.StockListByCategory, name='StockListByCategory'),
    url(r'^(?P<category_slug>[-\w]+)/brand/(?P<brand_slug>[-\w]+)/$', views.ProductListByBrand, name='ProductListByBrand'),
    url(r'^stock/(?P<category_slug>[-\w]+)/brand/(?P<brand_slug>[-\w]+)/$', views.StockListByBrand, name='StockListByBrand'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),
    url(r'^(?P<pk>\d+)/(?P<slug>[-\w]+)/reply/(?P<id>\d+)/$', views.reply_product, name='ProductReply'),
    url(r'^product_edit/(?P<id>\d+)/(?P<slug>[-\w]+)/$', ProductEdit.as_view(), name='ProductEdit'),
    url(r'^product_delete/(?P<pk>\d+)/(?P<slug>[-\w]+)/$', views.ProductDelete, name='ProductDelete')
]

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^basket_adding/$', views.basket_adding, name='basket_adding'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^orders/$', views.order_list, name='order_list'),
    url(r'^orders/search/$', views.order_search, name='order_search'),
    url(r'^orders/search_tph/$', views.order_search_tph, name='order_search_tph'),
    url(r'^orders/(?P<pk>\d+)/product_add/$', views.product_add, name='product_add'),
    url(r'^orders/(?P<pk>\d+)/edit/$', views.order_edit, name='order_edit'),
    url(r'^orders/(?P<pk>\d+)/delete/$', views.order_delete, name='order_delete'),


]

shop/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('myshop.urls', namespace='myshop')),
    url(r'^order/', include('orders.urls', namespace='orders' )),
    url(r'^accounts/', include('accounts.urls', namespace='account')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
        urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
from django.utils.text import Truncator
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'

    def get_absolute_url(self):
        return reverse('myshop: ProductListByCategory', args=[self.slug])

    def __unicode__(self):
        return u"%s"%(self.name)

class Brand(models.Model):
    name = models.CharField(max_length=200, db_index=True, blank=True, null=True, default=None)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, blank=True, null=True, default=None)
    category = models.ForeignKey(Category, related_name='brands', verbose_name='Категорія')
    class Meta:
        ordering = ['name']
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренди'


    def __unicode__(self):
        return u"%s"%(self.name)


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', verbose_name='Категорія', blank=True, null=True, default=None)
    brand = models.ForeignKey(Brand, related_name='products', verbose_name='Бренд', blank=True, null=True, default=None)
    name = models.CharField(max_length=200, db_index=True, verbose_name='Назва')
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True, verbose_name='Зображення товару')
    description = models.TextField(blank=True, verbose_name='Опис товару')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Ціна')
    stock = models.PositiveIntegerField(verbose_name='На складі')
    available = models.BooleanField(default=True, verbose_name='Доступний')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        index_together = [['id', 'slug']]
        verbose_name = 'Товар'
        verbose_name_plural = 'Товари'

    def get_absolute_url(self):
        return reverse('myshop:ProductDetail', args=[self.id, self.slug])

    def __unicode__(self):
        return u"%s"%(self.name)

class Reply(models.Model):
    message = models.TextField(max_length=4000, verbose_name='коментар')
    product = models.ForeignKey(Product, related_name='replies')
    author = models.ForeignKey(User, related_name='replies')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    parent = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = 'Коментар'
        verbose_name_plural = 'Коментарі'

    def __unicode__(self):
        reply = Truncator(self.message).chars(30)
        return u"%s"%(reply)

myshop/forms.py
from django import forms
from .models import Reply

class ReplyForm(forms.ModelForm):

    class Meta:
        model = Reply
        fields = ['message',]

myshop/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.views.generic import CreateView, UpdateView
from .models import Category, Product, Brand, Reply
from django.utils.text import slugify
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from django.template.loader import render_to_string
from .util import paginate
from .forms import ReplyForm
import json

# Create your views here.

def ProductList(request, category_slug=None):

    products = Product.objects.filter(available=True)
    context = paginate(products, 4, request, {}, var_name='products')
    return render(request, 'myshop/product/list.html',context )

def ProductStock(request):
    products = Product.objects.all()
    return render(request, 'myshop/product/stock.html', locals())

def ProductListByCategory(request, category_slug ):
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(available=True, category=category)
        brands = Brand.objects.filter(category=category)
        context = paginate(products, 4, request, {}, var_name='products')
    return render(request, 'myshop/product/list_by_category.html', context)

def StockListByCategory(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    context = {'products': products}
    data = dict()
    data['html_form'] = render_to_string('myshop/product/includes/partial_stock_list.html', context, request)
    return JsonResponse(data)


def ProductListByBrand(request, category_slug, brand_slug ):

    if category_slug:
        brands = get_object_or_404(Brand, category__slug=category_slug, slug=brand_slug)
        products = Product.objects.filter(available=True, brand=brands)
        context = paginate(products, 4, request, {}, var_name='products')
    return render(request, 'myshop/product/list_by_brand.html', context)

def StockListByBrand(request, category_slug, brand_slug):
    brands = get_object_or_404(Brand, category__slug=category_slug, slug=brand_slug)
    products = Product.objects.filter(available=True, brand=brands)
    context = {'products': products}
    data = dict()
    data['html_form'] = render_to_string('myshop/product/includes/partial_stock_list.html', context, request)
    return JsonResponse(data)


def ProductDetail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()
    replies = Reply.objects.filter(product=product)
    return render(request, 'myshop/product/detail.html', {'product': product, 'replies': replies})

class CreateProduct(CreateView):
    model = Product
    fields = ('category', 'brand', 'name', 'image', 'description', 'price', 'stock', 'available',)
    template_name = 'myshop/product/create_product.html'

    def form_valid(self, form):

        model = form.save(commit=False)
        model.slug = slugify(model.name)
        model.save()
        return redirect('myshop:CreateProduct')

class ProductEdit(UpdateView):
    model = Product
    fields = fields = ['name', 'category', 'brand', 'description', 'price', 'stock', 'image']
    template_name = 'myshop/product/product_edit.html'

    def get_success_url(self):
        return reverse('myshop:Stock')

def ProductDelete(request, pk, slug):
    product = get_object_or_404(Product, pk=pk, slug=slug)
    data = dict()
    if request.method == 'POST':
        product.delete()
        data['form_is_valid'] = True
        products = Product.objects.all()
        data['html_order_list'] = render_to_string('myshop/product/includes/partial_stock_list.html', {'products': products})
    else:
        context = {'product': product}
        data['html_form'] = render_to_string('myshop/product/product_delete.html', context, request)
    return JsonResponse(data)


def product_search_tph(request):
    q = request.GET.get('q', '')
    products = Product.objects.filter(name__icontains=q)
    data = []
    for product in products:
        new = {'q': product.name}
        if not new in data:
            data.append(new)
    return HttpResponse(json.dumps(data), content_type="application/json")

def product_search(request):
    data = dict()
    if request.method == 'POST':
        search = request.POST.get('search_product')
        products = Product.objects.filter(name__iexact=search)
        data['form_is_valid'] = True
        data['html_order_list'] = render_to_string('myshop/product/includes/partial_stock_list.html', {'products': products})

    return JsonResponse(data)

def reply_product(request, pk, slug, id):
    product = get_object_or_404(Product, pk=pk, slug=slug)
    data = dict()
    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            reply, created = Reply.objects.get_or_create(product=product, message=form.cleaned_data.get('message'), author=request.user)
            if int(id) > 0:
                reply.parent = int(id)
                reply.save()
            replies = Reply.objects.filter(product=product)
            data['form_is_valid'] = True

            data['html_order_list'] = render_to_string('myshop/product/includes/partial_replay_list.html', {'replies': replies, 'product': product})
    else:
        form = ReplyForm
        context = {'form': form, 'product': product}
        data['html_form'] = render_to_string('myshop/product/reply_add.html', context, request)
    return JsonResponse(data)

templates/myshop/base.html
{% load static  %}
{% load myshop_extras %}
<!DOCTYPE html>
<html xml:lang="uk">
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/typeahead.css' %}">
      {% block extra_css %}{% endblock extra_css %}
  </head>
  <body>


   {% include 'myshop/navbar.html' %}



    </nav>
   <div class="container">
      <div class="jumbotron" >
        <div class="container" >
          <h1 class="display-3">Вас вітає магазин Ера !</h1>
          <p></p>
          <p><a class="btn btn-primary btn-lg" href="#" role="button">Дізнатися більше &raquo;</a></p>
        </div>
      </div>
   </div>
    <section id="content row" class="container">

      {% block content %}{% endblock %}
    </section>
     <!-- Modal window  -->
         <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
                aria-labelledby="myModalLabel" aria-hidden="true">
             <div class="modal-dialog">
                 <div class="modal-content">
                     <div class="modal-header">
                         <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                             <span aria-hidden="true">&times;</span>
                         </button>
                         <h4 class="modal-title" id="myModalLabel" ><!-- --></h4>
                     </div>
                     <div class="modal-body"><!-- --></div>
                        <img class="modal-content" id="img00" >
                        <div id="caption"></div>
                     <div class="modal-footer"><!-- --></div>
                 </div>

             </div>
         </div>

    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/order.js' %}"></script>
    <script src="{% static 'js/typeahead.js' %}"></script>
    {% block extra_js %}{% endblock extra_js %}

  </body>

</html>

templates/myshop/checkout.html
{% extends 'myshop/base.html' %}
{% load static %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-lg-offset-2">
                <h3 class="text-center">Товари в корзині</h3>

                <form method="post" class="form-horizontal">{% csrf_token %}
                    <div class="form-group">
                        <div class="col-lg-4">
                            <label>Ім'я</label>
                            <input type="text" name="{{ form.name.html_name }}" class="form-control"
                               {% if user.is_authenticated %} value="{{ user.username }}" {% else %} value="{{ request.POST.username }}" {% endif %}>
                            <span class="form-error">{{ form.name.errors }}</span>
                        </div>

                    </div>
                    <div class="form-group">
                        <div class="col-lg-4">
                            <label>Телефон</label>
                            <input type="text" name="{{ form.phone.html_name }}" class="form-control"
                                {% if user.is_authenticated %} value= "{{ user.stprofile.mobile_phone }}" {% else %} value= "{{ request.POST.phone }}" {% endif %}>
                            <span class="form-error">{{ form.phone.errors }}</span>
                        </div>
                    </div>
                    <table class="table text-center">
                        <thead>
                            <tr>
                                <th>Назва товару</th>
                                <th>Кількість</th>
                                <th>Ціна за одиницю</th>
                                <th>Загальна вартість</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for product_in_basket in products_in_basket %}
                                <tr class="product-in-basket">
                                    <td>{{ product_in_basket.product.name }}</td>
                                    <td>
                                        <input value="{{ product_in_basket.nmb }}" type="number" class="product-in-basket-nmb"
                                               name="product_in_basket.nmb_{{ product_in_basket.id }}">
                                    </td>
                                    <td>
                                        <span class="product-in-basket-price-per-item">
                                            {{ product_in_basket.price_per_item }}
                                        </span>
                                    </td>
                                    <td>
                                        <span class="total-product-in-basket-amount">
                                            {{ product_in_basket.total_price }}
                                        </span>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div class="text-right">
                        <b>Сума замовлення: </b><span id="total_order_amount"></span>
                    </div>
                    <hr/>
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary btn-lg" onclick="alert('Замовлення прийнято !')">Замовити</button>
                    </div>

                </form>

            </div>

        </div>

    </div>

{% endblock content %}

templates/myshop/navbar.html
{% load myshop_extras %}

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #2687b4;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'myshop:ProductList' %}">Головна <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Адмінка
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'myshop:CreateProduct' %}">Додати товар</a>
          <a class="dropdown-item" href="{% url 'orders:order_list' %}">Замовлення</a>
          <a class="dropdown-item" href="{% url 'myshop:Stock' %}">Склад</a>
        </div>
      </li>


        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Категорії
        </a>

        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

          {% for cat in categories %}
          <li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="#">{{ cat.name }}</a>

            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'myshop:ProductListByCategory' cat.slug %}">Всі</a></li>
              {% for brand in cat.brands|in_category:cat %}
              <li><a class="dropdown-item" href="{% url 'myshop:ProductListByBrand' cat.slug brand.slug %}">{{ brand.name }}</a></li>
              {% endfor %}


            </ul>
          </li>
            {% endfor %}
        </ul>
      </li>
    </ul>

  </div>
    <div class="signup" style="font-size:17px;">
               <ul class="navbar-nav">
                {% if user.is_authenticated %}

                <li class="nav-item dropdown" style="margin-right: 7px;"><a class="dropdown" data-toggle="dropdown" href="#" style="color: white;"> {{user.username}}<span class="caret"></span> </a>

                    <ul class="dropdown-menu">
                        <li><a href="{% url 'account:my_account' %}">Мій акаунт</a></li>
                        <li><a href="{% url 'account:password_reset' %}">Змінити пароль</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'account:logout' %}">Вийти</a></li>

                    </ul>
                </li>
                <li class="nav-item"><a href="{% url 'account:logout' %}"><i class="fas fa-sign-out-alt fa-2x"></i></a></li>
                {% else %}
                <li class="nav-item"><a href="{% url 'account:signup' %}"><i class="fas fa-user-plus fa-2x"></i></a></li>
                <li class="nav-item"><a href="{% url 'social:begin' 'facebook' %}"> <i class="fab fa-facebook-square fa-2x"></i></a></li>
                <li class="nav-item"><a href="{% url 'account:login' %}"><i class="fas fa-sign-in-alt fa-2x"></i></a> </li>

                {% endif %}

                </ul>
                </div>
    <div class="nav navbar-nav navbar-right">

           <div class="basket-container">
               <a href="{% url 'orders:checkout' %}" class="basket"><i class="fas fa-shopping-cart fa-2x"></i><span id="basket_total_nmb">
                   {% if products_total_nmb %}
                    ({{ products_total_nmb }})
                   {% else %}
                    (0)
                   {% endif %}
               </span></a>
                <div class="basket-items d-none">
                    <ul >
                        {% for product_in_basket in products_in_basket %}
                            <li>
                                {{ product_in_basket.product.name }} {{ product_in_basket.nmb }} шт. по {{ product_in_basket.price_per_item }} грн.
                                <a class="delete-item" href="" data-product_id="{{ product_in_basket.id }}">x</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>


           </div>
    </div>
</nav>